version: "3"

services:
  backend:
    build: ./backend
    restart: always
    ports:
    - 3000
    volumes:
    - image_data:/data/images
    environment:
    - DB_URI=mongodb://db:27017/pixelgram-db

  frontend:
    build: ./frontend
    restart: always
    ports:
    - 4000:80

  db:
    image: mongo:3.4
    restart: always
    ports:
    - 27017
    volumes:
    - db_data:/data/db

volumes:
  db_data:
  image_data:
