version: "3"

services:
  backend:
    build: ./backend
    restart: always
    ports:
    - ${PORT}
    volumes:
    - image_data:/usr/src/app/${IMAGE_DIR}
    env_file:
    - .env

  frontend:
    build: ./frontend
    restart: always
    ports:
    - 4000:80

  db:
    image: mongo:3.4
    restart: always
    ports:
    - ${DB_PORT}
    volumes:
    - db_data:/data/db

volumes:
  db_data:
  image_data:
