version: "3"

services:
  backend:
    build: ./backend
    restart: always
    ports:
    - 3000
    volumes:
    - image_data:/data/images
    environment:
    - DATABASE_URI=mongodb://database:27017/pixelgram
    - PORT=3000
    - SECRET=7f40a8c2c68f47ef7b896586b012ae34

  frontend:
    build: ./frontend
    restart: always
    ports:
    - 4000:80

  database:
    build: ./database
    restart: always
    ports:
    - 27017
    volumes:
    - database_data:/data/db
    environment:
    - MONGO_INITDB_DATABASE=pixelgram

volumes:
  database_data:
  image_data:
