apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: pixelgram
    tier: backend
  ports:
  - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: pixelgram
    tier: backend
spec:
  selector:
    matchLabels:
      app: pixelgram
      tier: backend
  template:
    metadata:
      labels:
        app: pixelgram
        tier: backend
    spec:
      containers:
      - name: backend
        image: pixelgram/backend
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 200m
        env:
        - name: DATABASE_URL
          value: postgresql://postgres:kubernetes@database:5432/pixelgram
        - name: SECRET
          value: 7f40a8c2c68f47ef7b896586b012ae34
        - name: IMAGE_DIR
          value: /data/images
