apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: pixelgram
    tier: database
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: pixelgram
    tier: database
spec:
  selector:
    matchLabels:
      app: pixelgram
      tier: database
  template:
    metadata:
      labels:
        app: pixelgram
        tier: database
    spec:
      containers:
      - name: database
        image: pixelgram/database
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_DATABASE
          value: pixelgram
        volumeMounts:
        - mountPath: /data/db
          name: database-storage
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pv-claim
