apiVersion: v1
kind: ConfigMap
metadata:
  name: database-config
data:
  pg_hba.conf: |
    local all all trust
    host all all 127.0.0.1/32 md5
    host all all ::1/128 md5
    host all all all md5
---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: pixelgram
    tier: database
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: pixelgram
    tier: database
spec:
  selector:
    matchLabels:
      app: pixelgram
      tier: database
  template:
    metadata:
      labels:
        app: pixelgram
        tier: database
    spec:
      containers:
      - name: database
        image: localhost:5000/pixelgram/database
        imagePullPolicy: IfNotPresent
        args:
        - -c
        - hba_file=/etc/postgresql/pg_hba.conf
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-credentials
              key: postgres-password
        - name: POSTGRES_DB
          value: pixelgram
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: database-storage
        - mountPath: /etc/postgresql/pg_hba.conf
          name: database-config
          subPath: pg_hba.conf
      volumes:
      - name: database-storage
        persistentVolumeClaim:
          claimName: database-pvc
      - name: database-config
        configMap:
          name: database-config
