apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  selector:
    app: pixelgram
    tier: database
  ports:
  - port: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  labels:
    app: pixelgram
    tier: database
spec:
  selector:
    matchLabels:
      app: pixelgram
      tier: database
  template:
    metadata:
      labels:
        app: pixelgram
        tier: database
    spec:
      containers:
      - name: database
        image: pixelgram/database
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: kubernetes
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: database-storage
      volumes:
        - name: database-storage
          persistentVolumeClaim:
            claimName: database-pvc
