apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: pixelgram
    tier: frontend
  ports:
  - port: 4000
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: pixelgram
    tier: frontend
spec:
  selector:
    matchLabels:
      app: pixelgram
      tier: frontend
  template:
    metadata:
      labels:
        app: pixelgram
        tier: frontend
    spec:
      containers:
      - name: frontend
        image: pixelgram/frontend
        imagePullPolicy: Never
        ports:
        - containerPort: 80
