apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pv-claim
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
