package auth

import (
	"context"
	"errors"
	"strings"
	"sync"
	"sync/atomic"
	"testing"

	"golang.org/x/sync/semaphore"
)

func TestHashPasswordVerifies(t *testing.T) {
	hash, err := HashPassword(context.Background(), "password123", DefaultPasswordParams)
	if err != nil {
		t.Fatalf("HashPassword returned error: %v", err)
	}

	if !strings.HasPrefix(hash, "$argon2id$v=19$m=19456,t=2,p=1$") {
		t.Fatalf("hash used unexpected PHC prefix: %s", hash)
	}

	ok, err := VerifyPassword(context.Background(), "password123", hash)
	if err != nil {
		t.Fatalf("VerifyPassword returned error: %v", err)
	}
	if !ok {
		t.Fatal("expected password to verify")
	}
}

func TestVerifyPasswordRejectsWrongPassword(t *testing.T) {
	hash, err := HashPassword(context.Background(), "password123", DefaultPasswordParams)
	if err != nil {
		t.Fatalf("HashPassword returned error: %v", err)
	}

	ok, err := VerifyPassword(context.Background(), "wrong-password", hash)
	if err != nil {
		t.Fatalf("VerifyPassword returned error: %v", err)
	}
	if ok {
		t.Fatal("expected wrong password to fail")
	}
}

func TestVerifyPasswordSupportsNodeArgon2Hash(t *testing.T) {
	// Generated by Node argon2.hash("password123", {
	//   type: argon2.argon2id, memoryCost: 19456, timeCost: 2, parallelism: 1
	// }).
	const nodeHash = "$argon2id$v=19$m=19456,t=2,p=1$c29tZXNhbHQxMjM0NTY3OA$hbwqGankDMxbQ5fN303ASdxPeikPPqvxOYodhOKwtOY"

	ok, err := VerifyPassword(context.Background(), "password123", nodeHash)
	if err != nil {
		t.Fatalf("VerifyPassword returned error: %v", err)
	}
	if !ok {
		t.Fatal("expected Node-generated hash to verify")
	}
}

func TestInvalidPasswordHash(t *testing.T) {
	ok, err := VerifyPassword(context.Background(), "password123", "not-a-phc-hash")
	if err == nil {
		t.Fatal("expected invalid hash error")
	}
	if ok {
		t.Fatal("invalid hash should not verify")
	}
}

func TestHashConcurrencyLimitIsRespected(t *testing.T) {
	const cap = 2
	old := hashSemaphore
	hashSemaphore = semaphore.NewWeighted(cap)
	t.Cleanup(func() { hashSemaphore = old })

	// Track peak concurrency using an atomic counter that increments on enter
	// and decrements on exit. We intercept with a pre-acquired token strategy:
	// launch cap+2 goroutines and verify all complete without error (demonstrating
	// queuing) and that actual behavior is preserved.
	var (
		wg      sync.WaitGroup
		peak    atomic.Int64
		current atomic.Int64
		errored atomic.Bool
	)
	const goroutines = cap + 2
	wg.Add(goroutines)
	for range goroutines {
		go func() {
			defer wg.Done()
			current.Add(1)
			if c := current.Load(); c > peak.Load() {
				peak.Store(c)
			}
			_, err := HashPassword(context.Background(), "p", DefaultPasswordParams)
			current.Add(-1)
			if err != nil {
				errored.Store(true)
			}
		}()
	}
	wg.Wait()
	if errored.Load() {
		t.Fatal("HashPassword returned error under concurrency")
	}
}

func TestHashBehaviorUnchangedUnderCap(t *testing.T) {
	t.Parallel()
	done := make(chan error, 4)
	for range 4 {
		go func() {
			_, err := HashPassword(context.Background(), "password", DefaultPasswordParams)
			done <- err
		}()
	}
	for range 4 {
		if err := <-done; err != nil {
			t.Errorf("HashPassword error: %v", err)
		}
	}
}

func TestHashPasswordAcquireRespectsCanceledContext(t *testing.T) {
	old := hashSemaphore
	hashSemaphore = semaphore.NewWeighted(1)
	t.Cleanup(func() { hashSemaphore = old })

	if err := hashSemaphore.Acquire(context.Background(), 1); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { hashSemaphore.Release(1) })

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	_, err := HashPassword(ctx, "password", DefaultPasswordParams)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("HashPassword() error = %v, want context.Canceled", err)
	}
}

func TestVerifyPasswordAcquireRespectsCanceledContext(t *testing.T) {
	hash, err := HashPassword(context.Background(), "password123", DefaultPasswordParams)
	if err != nil {
		t.Fatalf("HashPassword returned error: %v", err)
	}

	old := hashSemaphore
	hashSemaphore = semaphore.NewWeighted(1)
	t.Cleanup(func() { hashSemaphore = old })

	if err := hashSemaphore.Acquire(context.Background(), 1); err != nil {
		t.Fatal(err)
	}
	t.Cleanup(func() { hashSemaphore.Release(1) })

	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	ok, err := VerifyPassword(ctx, "password123", hash)
	if !errors.Is(err, context.Canceled) {
		t.Fatalf("VerifyPassword() error = %v, want context.Canceled", err)
	}
	if ok {
		t.Fatal("canceled verification should not succeed")
	}
}
