package auth

import (
	"strings"
	"testing"
)

func TestHashPasswordVerifies(t *testing.T) {
	hash, err := HashPassword("password123", DefaultPasswordParams)
	if err != nil {
		t.Fatalf("HashPassword returned error: %v", err)
	}

	if !strings.HasPrefix(hash, "$argon2id$v=19$m=19456,t=2,p=1$") {
		t.Fatalf("hash used unexpected PHC prefix: %s", hash)
	}

	ok, err := VerifyPassword("password123", hash)
	if err != nil {
		t.Fatalf("VerifyPassword returned error: %v", err)
	}
	if !ok {
		t.Fatal("expected password to verify")
	}
}

func TestVerifyPasswordRejectsWrongPassword(t *testing.T) {
	hash, err := HashPassword("password123", DefaultPasswordParams)
	if err != nil {
		t.Fatalf("HashPassword returned error: %v", err)
	}

	ok, err := VerifyPassword("wrong-password", hash)
	if err != nil {
		t.Fatalf("VerifyPassword returned error: %v", err)
	}
	if ok {
		t.Fatal("expected wrong password to fail")
	}
}

func TestVerifyPasswordSupportsNodeArgon2Hash(t *testing.T) {
	// Generated by Node argon2.hash("password123", {
	//   type: argon2.argon2id, memoryCost: 19456, timeCost: 2, parallelism: 1
	// }).
	const nodeHash = "$argon2id$v=19$m=19456,t=2,p=1$c29tZXNhbHQxMjM0NTY3OA$hbwqGankDMxbQ5fN303ASdxPeikPPqvxOYodhOKwtOY"

	ok, err := VerifyPassword("password123", nodeHash)
	if err != nil {
		t.Fatalf("VerifyPassword returned error: %v", err)
	}
	if !ok {
		t.Fatal("expected Node-generated hash to verify")
	}
}

func TestInvalidPasswordHash(t *testing.T) {
	ok, err := VerifyPassword("password123", "not-a-phc-hash")
	if err == nil {
		t.Fatal("expected invalid hash error")
	}
	if ok {
		t.Fatal("invalid hash should not verify")
	}
}
