ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE SELECT, INSERT, UPDATE, DELETE ON TABLES FROM phasma_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE USAGE, SELECT ON SEQUENCES FROM phasma_app;
REVOKE SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public FROM phasma_app;
REVOKE USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public FROM phasma_app;
REVOKE USAGE ON SCHEMA public FROM phasma_app;
REVOKE CONNECT ON DATABASE phasma FROM phasma_app;
DROP ROLE IF EXISTS phasma_app;
