CREATE ROLE phasma_app;

GRANT CONNECT ON DATABASE phasma TO phasma_app;
GRANT USAGE ON SCHEMA public TO phasma_app;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO phasma_app;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO phasma_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO phasma_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO phasma_app;
